### ISSUE TITLE
Refactor repository structure

### ISSUE THREAD

**Issue by danieldf01** [danieldf01/TFG-decision-trees-sim#19]
Update the repository structure for a better overview and with a space for the prototypes to be able to merge them in the end:
- upload .tex/.bib files to the doc directory
- delete .idea directory
- make directory for prototypes

**Comment by danieldf01** [comment]
Repository structure has been refactored and unnecessary files have been removed

**Comment by clopezno** [comment]
This new repository structure will help us to agile the development process by facilitating the definition of the functional increments of the final product in each sprint. Good work @danieldf01 !

**Comment by danieldf01** [comment]
Exactly. Thank you! @clopezno
