### ISSUE TITLE
Decision trees algorithm ID3

### ISSUE THREAD

**Issue by danieldf01** [danieldf01/TFG-decision-trees-sim#2]
Get informed about the ID3 decision trees algorithm

**Comment by clopezno** [comment]
@danieldf01, I suggest you to add in the description of the task or in the subsequent comments details to understand it better. In this case it can be interesting to include the bibliographical references used or web links.

**Comment by danieldf01** [comment]
Used web links for learning about the ID3 algorithm and decision trees in general: 
https://www.ibm.com/topics/decision-trees#:~:text=A%20decision%20tree%20is%20a,internal%20nodes%20and%20leaf%20nodes.
https://www.youtube.com/watch?v=_L39rN6gz7Y&
https://www.youtube.com/watch?v=K-oGwFoCGU0
https://www.youtube.com/watch?v=coOTEc-0OGw&
https://www.youtube.com/watch?v=JO2wiZif2OM&
