### ISSUE TITLE
Learn Bootstrap

### ISSUE THREAD

**Issue by danieldf01** [danieldf01/TFG-decision-trees-sim#23]
Get informed about the basics of Bootstrap and how to use it

**Comment by danieldf01** [comment]
I learned the basic concepts and classes of Bootstrap 5 using these tutorials:
https://www.youtube.com/watch?v=Jyvffr3aCp0
https://www.w3schools.com/bootstrap5/bootstrap_get_started.php

**Comment by clopezno** [comment]
w3schools is a good reference for learning bootstrat and for documenting in the tfg report techniques and tools section.
