### ISSUE TITLE
[Improve Entropy prototypes] Tackle Codacy issues/duplicates

### ISSUE THREAD

**Issue by danieldf01** [danieldf01/TFG-decision-trees-sim#32]
Improve the code based on the issues/duplicates provided by Codacy

**Comment by danieldf01** [comment]
All issues have been tackled, the only remaining problems are 2 duplicate methods which occur because both prototypes use the methods "createRemoveButton" and "checkInput" which work in exactly the same way

**Comment by clopezno** [comment]
@danieldf01 to avoid duplicate code consider in a future sprint create/build a javascript library https://bugfender.com/blog/how-to-create-a-javascript-library/

**Comment by danieldf01** [comment]
> @danieldf01 to avoid duplicate code consider in a future sprint create/build a javascript library https://bugfender.com/blog/how-to-create-a-javascript-library/

Thank you for the idea! I will write it down as a possible task for a future sprint
